// Re-export everything from @shelvarr/db
// This maintains backward compatibility with @/lib/db imports
import { initDatabase as _initDatabase } from '@shelvarr/db';
import { join } from 'path';

export {
  getDb,
  getPool,
  closeDatabase,
  query,
  queryOne,
  execute,
  insertReturning,
  getSetting,
  setSetting,
  getAllSettings,
  getWantedBooks,
  getWantedBookById,
  addWantedBook,
  updateWantedBook,
  deleteWantedBook,
  isBookWanted,
  markWantedBookAsAcquired,
  getDownloadSourceConfigs,
  getDownloadSourceConfig,
  upsertDownloadSourceConfig,
  isSourceEnabled,
  getSourceStatusCache,
  getSourceStatus,
  updateSourceStatus,
  isStatusCacheStale,
  getReadProgress,
  upsertReadProgress,
  deleteReadProgress,
  getComicReadProgress,
  upsertComicReadProgress,
  deleteComicReadProgress,
  getComicReadProgressForVolume,
  getInProgressComics,
  getNextUpComics,
  getNextUpBooks,
  countNextUpBooks,
  replaceHardcoverStatuses,
  hardcoverStatusLabel,
  HARDCOVER_STATUS_LABELS,
  getWantToReadBooks,
  countWantToReadBooks,
  getHardcoverReadingBooks,
  countHardcoverReadingBooks,
  getEpubProgression,
  getLatestEpubProgression,
  upsertEpubProgression,
  getCachedComic,
  getCachedComicDetail,
  getCachedComics,
  upsertComicVolume,
  upsertComicVolumes,
  upsertComicDetail,
  upsertComicIssue,
  softDeleteComic,
  isComicDetailStale,
  getSyncChangesSince,
  buildFtsQuery,
  searchBooksFts,
  searchComicsFts,
  initDatabaseAsync,
  // Comic acquisition
  addComicDownload,
  getComicDownload,
  getComicDownloads,
  isComicDownloadActive,
  updateComicDownloadProgress,
  setComicDownloadState,
  deleteComicDownload,
  addComicDownloadHistory,
  getComicDownloadHistory,
  addToComicBlocklist,
  comicBlocklistContains,
  getComicBlocklist,
  removeFromComicBlocklist,
  clearComicBlocklist,
  getComicVolumeForMatching,
  // Comic library ownership
  getComicRootFolders,
  getComicRootFolder,
  addComicRootFolder,
  deleteComicRootFolder,
  countVolumesInRootFolder,
  getComicVolume,
  getComicVolumeByComicvineId,
  getManagedComicVolumes,
  isComicVolumeManaged,
  upsertManagedComicVolume,
  replaceComicIssuesFromMetadata,
  setComicVolumeMonitored,
  setComicIssueMonitored,
  setComicVolumeFolder,
  setComicVolumeCover,
  getComicVolumeCover,
  getComicVolumesNeedingRefresh,
  getComicVolumesWithMissingIssues,
  getComicFilesForVolume,
  getComicFilesForIssue,
  upsertComicFile,
  linkComicFileToIssues,
  deleteComicFile,
  pruneComicFiles,
  updateComicFilePath,
  getComicVolumeFileStats,
  refreshComicVolumeStats,
  getManagedComicDetail,
  getManagedIssueFile,
  getComicIssueFileRef,
  getComicIssueDetail,
  listComicVolumes,
} from '@shelvarr/db';

export type {
  ReadProgressRow,
  ComicReadProgressRow,
  ComicIssueProgress,
  InProgressComic,
  NextUpComic,
  EpubProgressionRow,
  BookSearchRow,
  ComicSearchRow,
  HardcoverStatusEntry,
  HardcoverStatusLabel,
  AddComicDownloadInput,
  AddComicBlocklistInput,
  ComicDownloadHistoryEntry,
  UpsertManagedVolumeInput,
  UpsertComicFileInput,
  ComicListSort,
} from '@shelvarr/db';

// Re-export types from @shelvarr/types that were previously defined here
export type {
  WantedBook,
  DownloadSourceConfig,
  SourceStatusCache,
} from '@shelvarr/types';

// Backwards-compatible wrapper: reads DB_PATH from env when no arg given
export function initDatabase(dbPath?: string) {
  const resolvedPath = dbPath
    || process.env['DB_PATH']
    || join(process.env['DATA_DIR'] || process.cwd() + '/data', 'shelvarr.db');
  return _initDatabase(resolvedPath);
}
